### ISSUE TITLE
Save Image to Disk

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#130]
The following request was made:

> Could you consider a "save to device" button after opening a photo? Currently there are 3 options: view, share, gallery.

Also, from [this Play Store review](https://play.google.com/store/apps/details?id=anabolicandroids.chanobol.reallysfw&reviewId=Z3A6QU9xcFRPRnkyWldDMVN1MHlEMGx0YklsSUstZ3FiQmExZHdmazJtY0ZVMmZfRGZuY1JvQVBQdFpLZm53U2JkdHRXbEIzV3JtemFjeExjWEphYnU5MWVj):

> Saving pics is weird. I have to click share and hit download with ES File Explorer, which is a separate app.

And from [this Play Store review](https://play.google.com/store/apps/details?id=anabolicandroids.chanobol.reallysfw&reviewId=Z3A6QU9xcFRPSEYxVnctODZSOUZ4SmpmeGlzN1VITWdVcEQ0TU9XUXBhNTJ6Sjg3SXhLdWQ4aUVhenhDU1FIa2Z4dm0wSG9fZ1J0NHdaTDhJaktrMlJnc2xr):

> Please add option to conveniently save image(s) to gallery

(I wonder what he means exactly by "gallery" - the Android media folder or a separate part of the application where all the saved images can be accessed. Might need to checkout Chanu to see its behavior)

**Comment by mitchross** [comment]
I might try to tackle this tonight.
