### ISSUE TITLE
Redesign PostView

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#142]
I found the following screenshot:

![1426238306704](https://cloud.githubusercontent.com/assets/211365/6653684/cd71b7d0-ca9b-11e4-96e7-726212dea92b.png)

Looks really good and having the replies button at the bottom is more usable (your read from top to bottom). Simply copy it. And don't forget to say that insipred by miko.

I just noticed that it's not so easy to integrate this design with the current Chanu based one. The "x Minutes ago", flags and image name and sizes should not be lost. Compare with current light theme of Chanobol:

![2015-03-14 21 43 06](https://cloud.githubusercontent.com/assets/211365/6653686/da50e692-ca9b-11e4-8698-9297801cfbd0.png)

**Comment by touhonoob** [comment]
wow

**Comment by eugenkiss** [comment]
Some screenshots of the result:

![2015-03-15 14 50 21](https://cloud.githubusercontent.com/assets/211365/6656520/58d4027e-cb2d-11e4-9827-790417ffe151.png)
![2015-03-15 14 51 08](https://cloud.githubusercontent.com/assets/211365/6656522/5cfbbc02-cb2d-11e4-86a4-b8ec8b84f990.png)
![2015-03-15 14 53 41](https://cloud.githubusercontent.com/assets/211365/6656525/60b120b2-cb2d-11e4-97a1-54d0318d171e.png)
![2015-03-15 14 54 05](https://cloud.githubusercontent.com/assets/211365/6656527/648b9dca-cb2d-11e4-8d71-42073a9977c0.png)
![2015-03-15 14 54 30](https://cloud.githubusercontent.com/assets/211365/6656529/68d45034-cb2d-11e4-873f-0272ec1f893f.png)
![2015-03-15 14 54 46](https://cloud.githubusercontent.com/assets/211365/6656530/6b835956-cb2d-11e4-9775-ddb4369dcff0.png)
