### ISSUE TITLE
Volume keys scrolling

### ISSUE THREAD

**Issue by ivantyr** [eugenkiss/chanobol#209]
A minor addition, scrolling through posts with the volume keys on a thread, could also be used while viewing images for next/previous

**Comment by eugenkiss** [comment]
Implementation notes: A setting to `prefs.xml`+`Settings` which is disabled by default. In `PostsActivity` a way has to be found to listen to volume up/down events and when such an event happens the `LinearLayoutManager` instance for the post list can be used to scroll to the next/previous post. The index should be clamped to be inside a defined interval.

**Comment by wadlieb** [comment]
I can tackle this one :+1:

**Comment by eugenkiss** [comment]
Great! FYI, I just realized that scrolling to the next post by index is stupid because a post might not fit into the screen so scrolling by a fixed pixel amount (maybe 80% of screen height? Or screenheight minus toolbar height or something) should be preferred to make it useful.
