### ISSUE TITLE
Settings Crash on Nexus 5 (Android M Preview)

### ISSUE THREAD

**Issue by mounteerie** [eugenkiss/chanobol#226]
I realise bugs on a development preview might not be priority, but here you go anyway.

Attempting to open settings immediately crashes Chanobol. Logcat here: https://gist.github.com/anonymous/c3b8f6b958296adfd527

**Comment by eugenkiss** [comment]
Thanks for letting me know and putting this information up.

**Comment by eugenkiss** [comment]
Fixed in https://github.com/eugenkiss/chanobol/commit/ffa65b8439f596f9556d11ec6db185b6fe1d1076
